# http://travis-ci.org/#!/sidnei/txstatsd
language: python
python:
    - 2.6
    - 2.7
install:
    - pip install -r requirements.txt --use-mirrors --install-option="--install-scripts=$VIRTUAL_ENV/bin" --install-option="--prefix=$VIRTUAL_ENV" --install-option="--install-lib=$VIRTUAL_ENV/lib"
    - pip install . --use-mirrors
script:
    - trial txstatsd